name: CI

on: [push]

jobs:
  iOS:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: TOSegmentedControlExample.xcodeproj
          scheme: TOSegmentedControlTests
          destination: platform=iOS Simulator,name=iPhone 16 Pro
          action: test
